# Copyright (c) EGOGE - All Rights Reserved.
# This software may be used and distributed according to the terms of the MIT license.

"""Build the wiki ``index.md`` from the current page list."""

from __future__ import annotations

from collections import defaultdict
from collections.abc import Iterable

from rlmkit.domain.wiki import PageType, WikiPage

INDEX_HEADER = "# Wiki index\n\nAuto-generated by rlmkit. Do not edit by hand.\n"

# Display order: most-load-bearing first.
PAGE_TYPE_DISPLAY_ORDER: tuple[PageType, ...] = (
    PageType.OVERVIEW,
    PageType.CONCEPT,
    PageType.WORKFLOW,
    PageType.PLAYBOOK,
    PageType.DECISION,
    PageType.INCIDENT,
    PageType.GLOSSARY,
)


def build_index(pages: Iterable[WikiPage]) -> str:
    """Render an index.md whose sections are grouped by PageType."""
    grouped: dict[PageType, list[WikiPage]] = defaultdict(list)
    for page in pages:
        grouped[page.type].append(page)

    out = [INDEX_HEADER]
    for ptype in PAGE_TYPE_DISPLAY_ORDER:
        bucket = grouped.get(ptype, [])
        if not bucket:
            continue
        out.append(f"\n## {ptype.value.capitalize()}\n")
        for page in sorted(bucket, key=lambda p: p.slug):
            out.append(f"- [{page.title}]({page.relative_path()})")
    out.append("")  # trailing newline
    return "\n".join(out)
